# Introduction to Tensor Flow

1. How does TensorFlow work?
2. Building a graph
3. What is the meaning of tensor?
4. Defining Multidimensional arreys using TensorFlow
5. Why Tensors?
6. How TensorFlow handles variables?
7. What are these placeholders and what do they do?
8. Learn operation using TensorFlow

### 1. How does TensorFlow work?

TensorFlow defines computations as Graphs, when we work with TensorFlow, it is the same as defining a series of operations in a Graph.

* Each Operation is a node
* Each Tensor is an edge

<img src='https://ibm.box.com/shared/static/a94cgezzwbkrq02jzfjjljrcaozu5s2q.png'>

Installing TensorFlow

In [1]:
!pip install grpcio==1.24.3
!pip install tensorflow==2.2.0

     |████████████████████████████████| 2.2 MB 5.1 MB/s 
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.44.0
    Uninstalling grpcio-1.44.0:
      Successfully uninstalled grpcio-1.44.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.
     |████████████████████████████████| 516.2 MB 4.2 kB/s 
     |████████████████████████████████| 2.9 MB 33.8 MB/s 
     |████████████████████████████████| 3.0 MB 47.4 MB/s 
     |████████████████████████████████| 454 kB 55.1 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboar

Importing TensorFlow

In [2]:
import tensorflow as tf
if not tf.__version__ == '2.2.0':
    print(tf.__version__)
    raise ValueError('please upgrade to TensorFlow 2.2.0, or restart your Kernel (Kernel->Restart & Clear Output)')

### 2. Building a graph
 
Each Operation `tf.Operation` is a node and each Tensor `tf.Tensor` is an edge in the graph.

Let's use `tf.function` and `Autograph`

Lets add 2 constants to our graph. For example, calling `tf.constant([2], name = 'constant_a')` adds a single `tf.Operation` to the default graph. This operation produces the value 2, and returns a `tf.Tensor` that represents the value of the constant.

In [14]:
a = tf.constant([2])
b = tf.constant([3])

Let's look at the tensor "a"

In [15]:
a

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>

it just shows the name, shape and type of the tensor in the graph.

Let's see the value by running the TensorFlow code

In [16]:
tf.print(a.numpy()[0])

2


Annotating the python functions with `tf.function` uses TensorFlow Autograph to create a TensorFlow static execution graph for the function. `tf.function` annotation tells TensorFlow Autograph to transform function add into TensorFlow control flow, which then defines the TensorFlow static execution graph.

Define your operations (In this case our constants and `tf.add`), define a Python function named add and **decorate** it with using the tf.function annotator.

In [17]:
@tf.function
def add(a,b):
    c = tf.add(a, b)  #Sum of the terms
    print(c)
    return c

In [10]:
result = add(a,b)
tf.print(result[0])

Tensor("Add:0", shape=(1,), dtype=int32)
5


### 3. What is the meaning of tensor?

In TensorFlow all data is passed between operations in a computation graph, and these are passed in the form of Tensors.

The word tensor from new latin means "that which stretches". It is a mathematical object that is named "tensor" because an early application of tensors was the study of materials stretching under tension. The contemporary meaning of tensors can be taken as multidimensional arrays.


The multidimensional arrays:
<br> <img src="https://ibm.box.com/shared/static/ymn0hl3hf8s3xb4k15v22y5vmuodnue1.svg"/>

* Zero dimension can be seen as a point, a single object or a single item.

* First dimension can be seen as a line, a one-dimensional array can be seen as numbers along this line, or as points along the line. One dimension can contain infinite zero dimension/points elements.

* Second dimension can be seen as a surface, a two-dimensional array can be seen as an infinite series of lines along an infinite line.

* Third dimension can be seen as volume, a three-dimensional array can be seen as an infinite series of surfaces along an infinite line.

* Fourth dimension can be seen as the hyperspace or spacetime, a volume varying through time, or an infinite series of volumes along an infinite line. And so forth on...

<img src="https://ibm.box.com/shared/static/kmxz570uai8eeg6i6ynqdz6kmlx1m422.png">

### 4. Defining Multidimensional arreys using TensorFlow

Let's try defining arrays using TensorFlow

In [13]:
scalar = tf.constant(2)
vector = tf.constant([5, 6, 2])
matrix = tf.constant([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
tensor = tf.constant( [ [[1, 2, 3], [2, 3, 4], [3, 4, 5]] , [[4, 5, 6], [5, 6, 7], [6, 7, 8]] , [[7, 8, 9], [8, 9, 10], [9, 10, 11]] ] )

print(f"Scalar (1 entry):\n {scalar}\n")
print(f"Vector (3 entries) :\n {vector}\n")
print(f"Matrix (3x3 entries):\n {matrix}\n")
print(f"Tensor (3x3x3 entries) :\n {tensor}\n")

Scalar (1 entry):
 2

Vector (3 entries) :
 [5 6 2]

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]]

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]



`tf.shape` returns the shape of the structure


In [26]:
print("The scalar dimension (1 entry):", scalar.shape)
print("The vector dimension (3 entries):", vector.shape)
print("The matrix dimension (3x3 entries):", matrix.shape)
print("The tensor dimension (3x3x3 entries):", tensor.shape)

The scalar dimension (1 entry): ()
The vector dimension (3 entries): (3,)
The matrix dimension (3x3 entries): (3, 3)
The tensor dimension (3x3x3 entries): (3, 3, 3)


In [31]:
matrix_one = tf.constant([[1, 2, 3], [2, 3, 4], [3, 4, 5]])
matrix_two = tf.constant([[2, 2, 2], [2, 2, 2], [2, 2, 2]])

@tf.function
def add():
    return tf.add(matrix_one, matrix_two) #Sum of the terms

print("Defined using tensorflow function :")
add_1_operation = add()
print(add_1_operation)

print("\nDefined using normal expressions :")
add_2_operation = matrix_one + matrix_two
print(add_2_operation)

Defined using tensorflow function :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)

Defined using normal expressions :
tf.Tensor(
[[3 4 5]
 [4 5 6]
 [5 6 7]], shape=(3, 3), dtype=int32)


With the regular symbol definition and also the TensorFlow function we were able to get an element-wise multiplication, also known as Hadamard product.

*But what if we want the regular matrix product?*

We then need to use another TensorFlow function called `tf.matmul()`

In [32]:
matrix_one = tf.constant([[2, 3], [3, 4]])
matrix_two = tf.constant([[2, 3], [3, 4]])

@tf.function
def mathmul():
  return tf.matmul(matrix_one, matrix_two)

mul_operation = mathmul()

print ("Defined using tensorflow function :")
print(mul_operation)

Defined using tensorflow function :
tf.Tensor(
[[13 18]
 [18 25]], shape=(2, 2), dtype=int32)


### 5. Why Tensors?

* The Tensor structure helps us by giving the freedom to shape the dataset in the way we want.
* it is particularly helpful when dealing with images, due to the nature of how information in images are encoded,

### 6. How TensorFlow handles variables?

TensorFlow variables are used to share and persist some stats that are manipulated by our program. That is, when you define a variable, TensorFlow adds a tf.Operation to your graph. Then, this operation will store a writable tensor value. So, you can update the value of a variable through each run.

Let's first create a simple counter, by first initializing a variable v that will be increased one unit at a time:

In [34]:
v = tf.Variable(0)

We now create a python method increment_by_one. This method will internally call td.add that takes in two arguments, the reference_variable to update, and assign it to the value_to_update it by.

In [35]:
@tf.function
def increment_by_one(v):
        v = tf.add(v, 1)
        return v

To update the value of the variable v, we simply call the increment_by_one method and pass the variable to it. We will invoke this method thrice. This method will increment the variable by one and print the updated value each time.

In [36]:
for i in range(3):
    v = increment_by_one(v)
    print(v)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


### 8. Learn operation using TensorFlow

Operations are nodes that represent the mathematical operations over the tensors on a graph. These operations can be any kind of functions, like add and subtract tensor or maybe an activation function.

tf.constant, tf.matmul, tf.add, tf.nn.sigmoid are some of the operations in TensorFlow. These are like functions in python but operate directly over tensors and each one does a specific thing.

In [37]:
a = tf.constant([5])
b = tf.constant([2])
c = tf.add(a,b)
d = tf.subtract(a,b)


print(f'c =: {c}')
print(f'd =: {d}')

c =: [7]
d =: [3]


tf.nn.sigmoid is an activation function, it's a little more complicated, but this function helps learning models to evaluate what kind of information is good or not.